language: php
php:
  - 7.4
services:
  - mysql
before_script:
  - composer install --no-interaction
addons:
  ssh_known_hosts:
    - oryxbot.com
branches:
  only:
    - prod
script:
  - vendor/bin/phpunit
after_script:
  - ssh -i ./deploykey root@oryxbot.com "cd /var/www/html && git fetch origin prod && git reset --hard origin/prod && git pull origin prod && npm install && npm run production"
before_install:
  - openssl aes-256-cbc -K $encrypted_37426564817b_key -iv $encrypted_37426564817b_iv
    -in deploykey.enc -out ./deploykey -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploykey
  - echo -e "Host oryxbot.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploykey
