language: php
php:
  - 7.4
services:
  - mysql
addons:
  ssh_known_hosts:
    - oryxbot.com
cache:
  directories:
    - node_modules
    - vendor
branches:
  only:
    - prod
before_script:
  - composer install --no-interaction
script:
  - vendor/bin/phpunit
  - ssh -i ./deploykey root@oryxbot.com "pkill -f 'php /var/www/html/discordapp/index.php' >> /dev/null 2>&1" || true
  - ssh -i ./deploykey root@oryxbot.com "cd /var/www/html && git fetch origin prod && git reset --hard origin/prod && git pull origin prod && composer install --no-interaction && npm install --no-interaction && npm run production"
  - ssh -i ./deploykey root@oryxbot.com "(echo '* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1')|crontab"
  - ssh -i ./deploykey root@oryxbot.com "nohup php /var/www/html/discordapp/index.php > /dev/null 2>&1 &"
before_install:
  - openssl aes-256-cbc -K $encrypted_37426564817b_key -iv $encrypted_37426564817b_iv
    -in deploykey.enc -out ./deploykey -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploykey
  - echo -e "Host oryxbot.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploykey
