version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    restart: always
    depends_on:
      - php
    labels:
      caddy: temp.oryxbot.com
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - reverse-proxy
      - default

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    working_dir: /app
    env_file: .env
    restart: always
    expose:
      - "9000"

networks:
  reverse-proxy:
    external: true
