version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    restart: always
    labels:
      caddy: temp.oryxbot.com, dashboard.oryxbot.com
      caddy.reverse_proxy: "{{upstreams 80}}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - storage:/app/storage
    networks:
      - reverse-proxy
      - default

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    restart: unless-stopped
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    environment:
      - SOKETI_DEBUG=1
      - DEFAULT_APP_ID='${PUSHER_APP_ID:-some-id}'
      - DEFAULT_APP_KEY='${PUSHER_APP_KEY:-app-key}'
      - DEFAULT_APP_SECRET='${PUSHER_APP_SECRET:-some-app-secret}'
      - PUSHER_HOST='${PUSHER_HOST:-127.0.0.1}'
      - PUSHER_PORT= '${PUSHER_PORT:-6001}'
      - PUSHER_SCHEME='${PUSHER_SCHEME:-http}' # or https
      - METRICS_SERVER_PORT=${SOKETI_METRICS_SERVER_PORT:-9601}
      - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-false}

  openobserve:
    image: 'public.ecr.aws/zinclabs/openobserve:v0.9.1'
    restart: unless-stopped
    labels:
      caddy: logs.oryxbot.com
      caddy.reverse_proxy: "{{upstreams 5080}}"
    volumes:
      - openobserve:/app/openobserve
    environment:
      - ZO_ROOT_USER_EMAIL='${OPEN_OBSERVE_ROOT_USER:-root@oryxbot.com}'
      - ZO_ROOT_USER_PASSWORD='${OPEN_OBSERVE_ROOT_PASSWORD:-***REMOVED***}'
      - ZO_DATA_DIR=/app/openobserve/data
    networks:
      - reverse-proxy
      - default

networks:
  reverse-proxy:
    external: true

volumes:
  storage:
  openobserve:
